version: 0.2

env:
  variables:
    BUCKET_NAME: "bookpython"  # Replace with your bucket name
    APP_ZIP: "bookstore-api.zip"
    CFN_STACK_NAME: "bookstore"
    CFN_TEMPLATE: "cloudformation.yaml"

phases:
  pre_build:
    commands:
      - echo "Setting up build environment..."
      - pip install awscli

  build:
    commands:
      - echo "Packaging Flask application..."
      - echo "List contents"
      - ls -latr
      - zip -r $APP_ZIP *

  post_build:
    commands:
      - echo "Uploading Flask app to S3..."
      - aws s3 cp $APP_ZIP s3://$BUCKET_NAME/
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file $CFN_TEMPLATE --stack-name $CFN_STACK_NAME --parameter-overrides S3BucketName=$BUCKET_NAME S3ObjectKey=$APP_ZIP KeyPairName=stockholmkeypair --capabilities CAPABILITY_IAM

artifacts:
  files:
    - $APP_ZIP
