version: "3.8"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet

  bookstore-api:
    build: . # Assumes Dockerfile is in the same directory
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      FLASK_ENV: development
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db_data:
